app/src/Entity/TransactionTemplate.php
<?php

namespace App\Entity;

use App\Enum\TransactionType;
use App\Repository\TransactionTemplateRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TransactionTemplateRepository::class)]
class TransactionTemplate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'transactionTemplates')]
    private Category $category;

    #[Assert\NotBlank(message: 'Name is required.')]
    #[ORM\Column(type: 'string', length: 255)]
    private string $name;

    #[Assert\GreaterThanOrEqual(value: 0, message: 'Position should be greater than or equal to 0.')]
    #[Assert\NotBlank(message: 'Position is required.')]
    #[ORM\Column(type: 'integer')]
    private int $position;

    #[Assert\NotBlank(message: 'Type is required.')]
    #[ORM\Column(type: 'string', length: 7, enumType: TransactionType::class)]
    private TransactionType $transactionType;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'transactionTemplates')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTransactionType(): ?TransactionType
    {
        return $this->transactionType;
    }

    public function setTransactionType(TransactionType $transactionType): self
    {
        $this->transactionType = $transactionType;

        return $this;
    }

    public function isIncome(): bool
    {
        return $this->transactionType === TransactionType::Income;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

app/src/Controller/Private/StatsController.php
<?php

namespace App\Controller\Private;

use App\Balance\Calculator;
use App\Stats\Category;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/stats', name: 'stats_')]
class StatsController extends AbstractController
{
    private Category $catStats;

    public function __construct(Category $catStats)
    {
        $this->catStats = $catStats;
    }

    #[Route('', name: 'index', methods: ['GET'])]
    public function index(Calculator $calculator): Response
    {
        return $this->render('stats/index.html.twig', [
            'catStats' => $this->catStats->calcAll(),
            'stats' => $calculator->getAllTimeBalance($this->getUser()),
        ]);
    }
}

app/templates/stats/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Stats | {{ parent() }}{% endblock %}
{% block headerText %}Stats{% endblock %}
{% block content %}
    <article class="min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <section class="w-full max-w-md space-y-8">
            <div class="view-container">
                <div class="px-4 py-5 sm:px-6">
                    <h2 class="font-bold text-2xl">All time</h2>
                </div>
                <div class="view-data-container">
                    <dl>
                        <div>
                            <dt>Income</dt>
                            <dd>{{ stats.income }}</dd>
                        </div>
                        <div>
                            <dt>Outcome</dt>
                            <dd>{{ stats.outcome }}</dd>
                        </div>
                        <div>
                            <dt>Savings</dt>
                            <dd>{{ stats.savings }}</dd>
                        </div>
                        <div>
                            <canvas id="cat-stats"></canvas>
                        </div>
                    </dl>
                </div>
            </div>
        </section>
    </article>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script defer>
        const ctx = document.getElementById('cat-stats');
        {% set amounts = [] %}
        {% set colors = [] %}
        {% set names = [] %}
        new Chart(ctx, {
            data: {
                labels: {{ catStats|map(v => v.name)|merge(names)|json_encode(constant('JSON_HEX_TAG'))|raw }},
                datasets: [{
                    backgroundColor: {{ catStats|map(v => v.color)|merge(colors)|json_encode(constant('JSON_HEX_TAG'))|raw }},
                    borderWidth: 1,
                    data: {{ catStats|map(v => v.amount)|merge(amounts)|json_encode(constant('JSON_HEX_TAG'))|raw }},
                    label: 'Amount',
                }],
            },
            options: {
                plugins: {
                    legend: {
                        display: false,
                    }
                }
            },
            type: 'bar',
        });
    </script>
{% endblock %}